---
title: "03results.Rmd"
output: html_document
---



```{r pacotes3, echo=FALSE, warning=FALSE, message=FALSE}
require(tidyverse)
require(magrittr)
require(reshape2)
require(rstanarm)
require(bayesplot)
require(ggplot2)
require(gridExtra)
```


```{r arvHaEspecie, echo=FALSE, warning=FALSE, message=FALSE}
arvHaEspecie = invMerged %>%
  drop_na(scientific.name) %>%
  filter(DBH >= 10) %>%
  group_by(area, year, plot, subplot, GrupoEco, scientific.name) %>% 
  summarise(ntree = sum(eqTree)) %>%
  drop_na(ntree) %>%
  group_by(area, year, plot, scientific.name) %>%
  summarise(ntree = mean(ntree)) %>%
  group_by(area, year,  scientific.name) %>%
  summarise(ntree = sum(ntree)) %>%
  left_join(parcelasArea) %>%
  mutate(arvha = ntree / nplots) %>%
  group_by(area, scientific.name) %>%
  summarise(arvha = mean(arvha)) %>%
  group_by(scientific.name) %>%
  summarise(arvha = mean(arvha)) %>%
  filter(scientific.name %in%speciesOfInterest) %>%
  mutate(arvProp=arvha/sum(arvha)*100)

```


```{r incInteresse, echo=FALSE, warning= FALSE, message=FALSE}

incrementoInteresse = incInteresse%>%
  group_by(scientific.name) %>%
  summarise(inc = median(incAnual),
            incIQR = IQR(incAnual, na.rm = TRUE),
            rIncA = median(rInc),
            rIncIQR = IQR(rInc, na.rm = TRUE))

```


```{r tabelaDasEspeciesDeInteresse, echo=FALSE, warning= FALSE, message=FALSE }

knitr::kable(
  inner_join(arvHaEspecie, incrementoInteresse, by="scientific.name") %>%
    select(scientific.name, inc, incIQR,  rIncA, rIncIQR),
  caption = 'Resumo das Espécies de Interesse.'
    )

```




```{r graficoDDInc, echo=FALSE, warning=FALSE, message=FALSE, fig.cap = 'Distribuição do incremento diamétrico anual para cada espécie por centro de classe.'}

incMedSpecies = incInteresse %>%
  filter(scientific.name %in%speciesOfInterest) %>%
  group_by(scientific.name, cc) %>%
  summarise(incMediaAnual = mean(incAnual))

ggplot(incMedSpecies, aes(cc, incMediaAnual)) + 
  geom_col() +
  xlab('Diameter distribution') + ylab('Incremento Anual') +
  ylim(0, 2.5) +
    theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     axis.line = element_line(colour = "black"))+
  facet_wrap(~factor(scientific.name,levels=c("Eschweilera coriacea", " Lecythis idatimon", "Manilkara huberi", "Tetragastris panamensis", "Inga marginata", "Lecythis lurida", "Pseudopiptadenia suaveolens", "Inga thibaudiana",  "Dialium guianense", "Neea oppositifolia", "Jacaranda copaia", "Nectandra cuspidata", "Laetia procera", "Tachigali paniculata",  "Minquartia guianensis", "Inga alba",  "Carapa guianensis", " Licania heteromorpha", "Zollernia paraensis", "Lecythis pisonis", "Dinizia excelsa", "Ocotea cernua", " Poecilanthe effusa")), ncol=5)

```



```{r graficoDDSpecies, echo=FALSE, warning=FALSE, message=FALSE, fig.cap = 'Distribuição diamétrica para as espécies de interesse.'}

numeroArvores = invMerged %>%
  filter(scientific.name %in%speciesOfInterest) %>%
  group_by(area, year, plot, subplot, GrupoEco, scientific.name, cc) %>% 
  summarise(ntree = sum(eqTree))  %>%
  drop_na(ntree) %>%
  group_by(area, year, plot, scientific.name, cc)%>%
  summarise(ntree = mean(ntree)) %>%
  group_by(area, year, scientific.name, cc)%>%
  summarise(ntree = sum(ntree)) %>%
  left_join(parcelasArea) %>%
  mutate(arvha = ntree/ nplots) %>%
  group_by(area, scientific.name, cc) %>%
  summarise(arvha = mean(arvha)) %>%
  group_by(scientific.name, cc) %>%
  summarise(arvha = mean(arvha), med= n())
    


ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
  xlab('Diameter distribution') + ylab('Trees per hectare') +
    theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     axis.line = element_line(colour = "black"))+
  facet_wrap(~factor(scientific.name,levels=c("Eschweilera coriacea", " Lecythis idatimon", "Manilkara huberi", "Tetragastris panamensis", "Inga marginata", "Lecythis lurida", "Pseudopiptadenia suaveolens", "Inga thibaudiana",  "Dialium guianense", "Neea oppositifolia", "Jacaranda copaia", "Nectandra cuspidata", "Laetia procera", "Tachigali paniculata",  "Minquartia guianensis", "Inga alba",  "Carapa guianensis", " Licania heteromorpha", "Zollernia paraensis", "Lecythis pisonis", "Dinizia excelsa", "Ocotea cernua", " Poecilanthe effusa")), ncol=5)

```



```{r graficoDDGrupoEcoAcumulado, echo=FALSE, warning=FALSE, message=FALSE, fig.cap = 'Distribuição diamétrica acumulada para as espécies de interesse.'}

numeroArvores = invMerged %>%
  filter(scientific.name %in%speciesOfInterest) %>%
  group_by(area, year, plot, subplot, GrupoEco, scientific.name, cc) %>% 
  summarise(ntree = sum(eqTree))  %>%
  drop_na(ntree) %>%
  group_by(area, year, plot, scientific.name, cc)%>%
  summarise(ntree = mean(ntree)) %>%
  group_by(area, year, scientific.name, cc)%>%
  summarise(ntree = sum(ntree)) %>%
  left_join(parcelasArea) %>%
  mutate(arvha = ntree/ nplots) %>%
  group_by(area, scientific.name, cc) %>%
  summarise(arvha = mean(arvha)) %>%
  group_by(scientific.name, cc) %>%
  summarise(arvha = mean(arvha), 
            med= n())%>%
    filter(med >1)


arvAcumuladas = c()
centroClasse = c()
speciesInteresse = c()

for(s in unique(numeroArvores$scientific.name)){
  arvoresPorSpecies = subset(numeroArvores,  scientific.name == s)
  acumulado = 0
  for(i in seq(15, max(arvoresPorSpecies$cc), 10)){
    if(i %in% arvoresPorSpecies$cc){
      speciesInteresse= c(speciesInteresse, s)
      centroClasse = c(centroClasse, i)
      acumulado = acumulado + as.numeric(arvoresPorSpecies[arvoresPorSpecies$cc == i, 'arvha'])
      arvAcumuladas = c(arvAcumuladas, acumulado)
    } else {
      speciesInteresse = c( speciesInteresse, s)
      centroClasse = c(centroClasse, i)
      acumulado = acumulado + 0
      arvAcumuladas = c(arvAcumuladas, acumulado)
    }
  }
}

numeroArvoresAcumulado = data.frame(speciesInteresse, centroClasse, arvAcumuladas)

ggplot(numeroArvoresAcumulado, aes(centroClasse, arvAcumuladas)) + geom_col() +
  xlab('Diameter distribution') + ylab('Accumulated trees per hectare') +
    theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     axis.line = element_line(colour = "black"))+
  facet_wrap(~factor(speciesInteresse,levels=c("Eschweilera coriacea", " Lecythis idatimon", "Manilkara huberi", "Tetragastris panamensis", "Inga marginata", "Lecythis lurida", "Pseudopiptadenia suaveolens", "Inga thibaudiana",  "Dialium guianense", "Neea oppositifolia", "Jacaranda copaia", "Nectandra cuspidata", "Laetia procera", "Tachigali paniculata",  "Minquartia guianensis", "Inga alba",  "Carapa guianensis", " Licania heteromorpha", "Zollernia paraensis", "Lecythis pisonis", "Dinizia excelsa", "Ocotea cernua", " Poecilanthe effusa")), ncol=5)
```


##Filtragem de espécies comerciais


```{r incInteresse, echo=FALSE, warning= FALSE, message=FALSE}

incrementoC = incComercial%>%
  group_by(scientific.name) %>%
  summarise(inc = median(incAnual),
            incIQR = IQR(incAnual, na.rm = TRUE),
            rIncA = median(rInc),
            rIncIQR = IQR(rInc, na.rm = TRUE))

```


```{r tabelaEspecieisComerciais, echo=FALSE, warning= FALSE, message=FALSE}

knitr::kable(
  inner_join(arvHaEspecie, incrementoC, by="scientific.name") %>%
    select(scientific.name, inc, incIQR,  rIncA, rIncIQR),
  caption = 'Resumo das Espécies de Interesse.'
    )


```




```{r distribuicaoIncComercial, echo=FALSE, message=FALSE, warning=FALSE}
incMedC = incComercial %>%
  filter(scientific.name %in%speciesOfInterest) %>%
   group_by(scientific.name, cc) %>%
  summarise(incMediaAnual = mean(incAnual))

ggplot(incMedC, aes(cc, incMediaAnual)) + 
  geom_col() +
  xlab('Diameter distribution') + ylab('Incremento Anual') +
  ylim(0, 2.5) +
    theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     axis.line = element_line(colour = "black"))+
  facet_wrap(~factor(scientific.name,levels=c("Carapa guianensis", "Dinizia excelsa","Eschweilera coriacea","Jacaranda copaia","Laetia procera","Lecythis lurida", "Lecythis pisonis", "Pseudopiptadenia suaveolens")), ncol=2)

```


```{r graficoDDSpeciesComerciais, echo=FALSE, warning=FALSE, message=FALSE, fig.cap = 'Distribuição diamétrica para as espécies comerciais.'}

numeroArvores = invMerged %>%
  filter(scientific.name %in%speciesOfInterest) %>%
  filter(comercial == 1) %>%
  group_by(area, year, plot, subplot, GrupoEco, scientific.name, cc) %>% 
  summarise(ntree = sum(eqTree))  %>%
  drop_na(ntree) %>%
  group_by(area, year, plot, scientific.name, cc)%>%
  summarise(ntree = mean(ntree)) %>%
  group_by(area, year, scientific.name, cc)%>%
  summarise(ntree = sum(ntree)) %>%
  left_join(parcelasArea) %>%
  mutate(arvha = ntree/ nplots) %>%
  group_by(area, scientific.name, cc) %>%
  summarise(arvha = mean(arvha)) %>%
  group_by(scientific.name, cc) %>%
  summarise(arvha = mean(arvha),
            med=n()) 
    


ggplot(numeroArvores, aes(cc, arvha)) + geom_col() +
  xlab('Diameter distribution') + ylab('Trees per hectare') +
    theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     axis.line = element_line(colour = "black"))+
  facet_wrap(~factor(scientific.name,levels=c("Carapa guianensis", "Dinizia excelsa","Eschweilera coriacea","Jacaranda copaia","Laetia procera","Lecythis lurida", "Lecythis pisonis", "Pseudopiptadenia suaveolens")), ncol=4)


```



```{r graficoDDAcumuladoEspComerciais, echo=FALSE, warning=FALSE, message=FALSE, fig.cap = 'Distribuição diamétrica acumulada para as espécies comerciais.'}
numeroArvores = invMerged %>%
  filter(scientific.name %in%speciesOfInterest) %>%
  filter(comercial == 1) %>%
  group_by(area, year, plot, subplot, GrupoEco, scientific.name, cc) %>% 
  summarise(ntree = sum(eqTree))  %>%
  drop_na(ntree) %>%
  group_by(area, year, plot, scientific.name, cc)%>%
  summarise(ntree = mean(ntree)) %>%
  group_by(area, year, scientific.name, cc)%>%
  summarise(ntree = sum(ntree)) %>%
  left_join(parcelasArea) %>%
  mutate(arvha = ntree/ nplots) %>%
  group_by(area, scientific.name, cc) %>%
  summarise(arvha = mean(arvha)) %>%
  group_by(scientific.name, cc) %>%
  summarise(arvha = mean(arvha))

arvAcumuladas = c()
centroClasse = c()
speciesInteresse = c()

for(s in unique(numeroArvores$scientific.name)){
  arvoresPorSpecies = subset(numeroArvores,  scientific.name == s)
  acumulado = 0
  for(i in seq(15, max(arvoresPorSpecies$cc), 10)){
    if(i %in% arvoresPorSpecies$cc){
      speciesInteresse= c(speciesInteresse, s)
      centroClasse = c(centroClasse, i)
      acumulado = acumulado + as.numeric(arvoresPorSpecies[arvoresPorSpecies$cc == i, 'arvha'])
      arvAcumuladas = c(arvAcumuladas, acumulado)
    } else {
      speciesInteresse = c( speciesInteresse, s)
      centroClasse = c(centroClasse, i)
      acumulado = acumulado + 0
      arvAcumuladas = c(arvAcumuladas, acumulado)
    }
  }
}

numeroArvoresAcumulado = data.frame(speciesInteresse, centroClasse, arvAcumuladas)

ggplot(numeroArvoresAcumulado, aes(centroClasse, arvAcumuladas)) + geom_col() +
  xlab('Diameter distribution') + ylab('Accumulated trees per hectare') +
    theme_bw() + theme(panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(),
                     panel.background = element_blank(),
                     axis.line = element_line(colour = "black"))+
  facet_wrap(~factor(speciesInteresse,levels=c("Carapa guianensis", "Dinizia excelsa","Eschweilera coriacea","Jacaranda copaia","Laetia procera","Lecythis lurida", "Lecythis pisonis", "Pseudopiptadenia suaveolens")), ncol=4)
```